FROM debian:12

WORKDIR app/
COPY /app /app/

RUN apt-get update -y
RUN apt-get install -y python3 python3-pip 
RUN pip3 install --break-system-packages -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]