FROM debian:12

WORKDIR app/
COPY /app /app/

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends python3 python3-pip  && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    pip3 install --break-system-packages -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]