FROM alpine:3.18

WORKDIR app/
COPY /app /app/

RUN apk add  --no-cache python3 py3-pip && \
    pip3 install --break-system-packages -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]