FROM debian:12

WORKDIR app/
COPY /app /app/

RUN apt-get update -y
RUN apt-get install -y python3 python3-pip 
RUN pip3 install --break-system-packages -r requirements.txt

CMD ["python3", "-m", "main.py"]